apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - name: port-80
    port: 80
    targetPort: 80
  selector:
    service: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
