apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: redis-master
  name: redis-master
spec:
  ports:
  - name: port-6379
    port: 6379
    targetPort: 6379
  selector:
    service: redis-master
  type: ClusterIP
status:
  loadBalancer: {}
