apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: gitlab
  name: gitlab
spec:
  ports:
  - name: port-80
    port: 80
    targetPort: 80
  - name: port-22
    port: 22
    targetPort: 1022
  selector:
    service: gitlab
  type: LoadBalancer
status:
  loadBalancer: {}
