apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: postgresql
  name: postgresql
spec:
  ports:
  - name: port-5432
    port: 5432
    targetPort: 5432
  selector:
    service: postgresql
  type: ClusterIP
status:
  loadBalancer: {}
