apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: redis
  name: redis
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: redis
    spec:
      containers:
      - image: redis:3.0
        name: redis-0
        ports:
        - containerPort: 6379
          name: port-6379
        resources: {}
status: {}
