apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  ports:
  - name: port-5000
    port: 5000
    targetPort: 5000
  selector:
    service: web
  type: ClusterIP
status:
  loadBalancer: {}
