apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: web
    spec:
      containers:
      - image: tuna/docker-counter23
        name: web-0
        ports:
        - containerPort: 5000
          name: port-5000
        resources: {}
status: {}
