apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: db
  name: db
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: db
    spec:
      containers:
      - image: postgres:9.4
        name: db-0
        ports:
        - containerPort: 5432
          name: port-5432
        resources: {}
status: {}
