apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: db
  name: db
spec:
  ports:
  - name: port-5432
    port: 5432
    targetPort: 5432
  selector:
    service: db
  type: ClusterIP
status:
  loadBalancer: {}
