apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: result
  name: result
spec:
  ports:
  - name: port-8081
    port: 8081
    targetPort: 80
  selector:
    service: result
  type: LoadBalancer
status:
  loadBalancer: {}
