apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: result
  name: result
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: result
    spec:
      containers:
      - image: tmadams333/example-voting-app-result:latest
        name: result-0
        ports:
        - containerPort: 80
          name: port-80
        resources: {}
status: {}
