apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: vote
  name: vote
spec:
  ports:
  - name: port-80
    port: 80
    targetPort: 80
  selector:
    service: vote
  type: LoadBalancer
status:
  loadBalancer: {}
