apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: vote
  name: vote
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: vote
    spec:
      containers:
      - image: docker/example-voting-app-vote:latest
        name: vote-0
        ports:
        - containerPort: 80
          name: port-80
        resources: {}
status: {}
