apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: mongo
  name: mongo
spec:
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: mongo
    spec:
      containers:
      - image: mongo
        name: mongo-0
        ports:
        - containerPort: 27017
          name: port-27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-persistent-storage
      volumes:
      - emptyDir: {}
        name: mongo-persistent-storage
status: {}
