apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: mongo
  name: mongo
spec:
  ports:
  - name: port-27017
    port: 27017
    targetPort: 27017
  selector:
    service: mongo
  type: LoadBalancer
status:
  loadBalancer: {}
