apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  ports:
  - name: port-80
    port: 80
    targetPort: 3000
  selector:
    service: web
  type: LoadBalancer
status:
  loadBalancer: {}
