apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: web
    spec:
      containers:
      - image: surajnarwade/myapp
        name: web-0
        ports:
        - containerPort: 3000
          name: port-3000
        resources: {}
status: {}
