apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: phabricator
  name: phabricator
spec:
  ports:
  - name: port-80
    port: 80
    targetPort: 80
  selector:
    service: phabricator
  type: LoadBalancer
status:
  loadBalancer: {}
